require: rubocop-rspec

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'

  TargetRubyVersion: 2.7

Lint/BooleanSymbol:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - 'Gemfile'

Metrics/ModuleLength:
  Enabled: false
  Exclude:
    - 'spec/**/*.rb'

Metrics/BlockLength:
  Enabled: false
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstParameterIndentation:
  Enabled: false

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/ClosingParenthesisIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Layout/HashAlignment:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/PredicateMatcher:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Max: 50

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Bundler/OrderedGems:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

RSpec/DescribeClass:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Style/Alias:
  EnforcedStyle: prefer_alias_method
